{
  "runnable": false,
  "phase": "seed",
  "error_type": "RuntimeError",
  "message": "Traceback (most recent call last):\n  File \"/home/wan00559/baseline/utils/compile_and_run.py\", line 223, in compare_and_bench\n    test_out, _ = _run_once(test_model, inp, dev)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/baseline/utils/compile_and_run.py\", line 127, in _run_once\n    out = model(*inp)\n          ^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1751, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1762, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/baseline/run/20250822_165826_batch_first5/16_ConvTranspose2d_Mish_Add_Hardtanh_Scaling/code/kernel_20250822_165852.py\", line 78, in forward\n    x = self.fused_ops.fused_ops_cuda(x, self.add_value, self.scale)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: module 'fused_ops' has no attribute 'fused_ops_cuda'\n"
}